### PR TITLE
Add noisebridge.io

### PR DESCRIPTION
**Pull request by SuperQ**
* Add noisebridge.io to DNS service.
* Add redirect from noisebride.io to noisebridge.net.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
cc @sunjam

**Comment by elimisteve** [comment]
LGTM :+1:

**Comment by elimisteve** [comment]
I don't know precisely which server noisebridge.io should point to -- @SuperQ is in better position to make that call -- but this seems fine to me.

**Comment by SuperQ** [comment]
@elimisteve The domain is currently just parked, never been used. I figure this is better than nothing.

**Comment by sunjam** [comment]
@SuperQ Is there a specific action that needs to be taken, or is this just for the record of what happened?  My understanding is DNS is already handled through our Gandi group.  I see merge is blocked pending @elimisteve review.

**Review by elimisteve — APPROVED** [review]
I commented "LGTM :+1:" 9 months ago but didn't realize the merge couldn't actually happen unless I left an official review, oops.

**Comment by elimisteve** [comment]
@SuperQ Please redeploy, thanks

**Pull request merged**
