### PR TITLE
Marcidy/maintainers - adding MAINTANERS.md

### PR DESCRIPTION
**Pull request by marcidy**
adding MAINTAINERS.md

### CODE REVIEW

**Comment by SuperQ** [comment]
Should we clarify a scope for what "infrastructure" means?

**Comment by marcidy** [comment]
Probably.
Physical networking infrastructure: Monkeybrains equipment, our equipment
Sanctity of The Rack
Hackerspace Network (i.e. responsibility for the physical space networking)
Noisebridge.net (is this sufficient or would you say zone file, dns, etc etc)
back-ups
deployment of ansible playbooks

anything else?

**Comment by SuperQ** [comment]
Earl/access control

**Comment by marcidy** [comment]
poke @SuperQ

**Pull request merged**
