### PR TITLE
Correct the confusing statement about 'next year' when its actually this year.

### PR DESCRIPTION
**Pull request by metasyn**
Someone brought this up at the meeting tonight - kinda confusing, might be leading people to think that they have a lot more time to get their shit together.

### CODE REVIEW

**Comment by rizend** [comment]
Thanks for making a PR for this!

**Comment by metasyn** [comment]
@rizend :)

I wasn't sure how changes here get deployed to the actual site - I know the site uses ansible (I was reading in here) - but am curious to learn how ya'll actually make the changes live.

**Comment by rizend** [comment]
Someone with access to whatever servers the changes affect has to deploy the change on those servers by running `ansible-playbook site.yml`.  These particular changes affect [noisebridge-net](https://github.com/noisebridge/infrastructure/blob/master/hosts.yml#L39) which is an alias for m3 (m3.noisebridge.net), the server that actually runs the site.  As I do not have access to m3, someone else will have to deploy it.  TL;DR: we don't auto deploy stuff right now (with one exception) so someone with access has to pull down the latest changes manually and run ansible.

**Comment by metasyn** [comment]
Got it - thanks for the clarification

**Pull request merged**
