### PR TITLE
Add victor to commuinty outreach email address

### PR DESCRIPTION
**Pull request by ruthgrace**
mostly for hack comedy night stuff (which victor organizes), potentially other outreach stuff

### CODE REVIEW

**Comment by SuperQ** [comment]
Oh, this aliases file is obsolete. The aliases are now controlled by a series of files.

See: `group_vars/noisebridge-net/alias_*.yml`

**Comment by ruthgrace** [comment]
Oh, whoops, thanks, that makes sense! Will fix in a bit

**Comment by SuperQ** [comment]
Yea, no problem, I forgot to delete the old aliases file when doing the refactoring.

**Comment by ruthgrace** [comment]
thank you Ben!

**Pull request merged**
