### PR TITLE
Adding a fundraising thermometer to the home page.

### PR DESCRIPTION
**Pull request by masparasol**
Sorry I could not figure out Bulma so I inlined the CSS. The thermometer needs to be updated manually.

### CODE REVIEW

**Comment by SuperQ** [comment]
Let's put this on a wiki page instead. Then there's no need to update the homepage.

**Comment by masparasol** [comment]
OK, it was suggested to put it on the home page in the finance work group of slack, but either way. I will see what the wiki page looks like...

**Comment by tdfischer** [comment]
> Let's put this on a wiki page instead. Then there's no need to update the homepage.

The homepage should absolutely be showing our donation progress somehow. What can we do that isn't a thermometer that still gets a big ole honkin' display of how well we're doing?

**Comment by SuperQ** [comment]
@tdfischer Mostly I think we should do better than having to manually update an html file with the thermometer data.

But, this is why we had the wiki be the home page in the first place. There was no need to manually edit HTML and push it to a server. Just click edit. :smirk:

**Comment by masparasol** [comment]
How fast do we expect money to be pouring in? Sure it would be nice to have an API to our total progress, but making a weekly or bi-weekly update to the thermometer should be fine. It is changing like 2 items. No big deal...

**Comment by tdfischer** [comment]
We can have real-time data pulled from littlegreenlight at any frequency we desire.

On February 20, 2019 10:29:23 AM PST, masparasol <notifications@github.com> wrote:
>How fast do we expect money to be pouring in? Sure it would be nice to
>have an API to our total progress, but making a weekly or bi-weekly
>update to the thermometer should be fine. It is changing like 2 items.
>No big deal...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/noisebridge/infrastructure/pull/147#issuecomment-465698962

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marcidy** [comment]
@rizend do you have any opinion about this?

**Comment by rizend** [comment]
WRT to the general idea, I agree with this:
> Mostly I think we should do better than having to manually update an html file with the thermometer data.
I think a better solution to this is to have an image automatically generated server side from whatever data source we want to use.  This would make having a bunch of custom CSS unnecessary and changes to the data would automatically be reflected in the thermometer without deploying new code.

**Comment by marcidy** [comment]
@masparasol Thanks for the PR, sorry it took so long to review, a lot of us spent all our "Noisebridge" time on the gala.  I think we want to go with something like @rizend mentioned above.  Would you be up for that?

**Comment by masparasol** [comment]
The blocks for me are:
1. Where is the data source that quantifies our current fundraising effort?
2. I am not sure I have the technical ability to poll the API and automatically update.

Thanks for the interest and what you are doing! :)

**Comment by marcidy** [comment]
Thanks! thank you for helping!

For now maybe you could use a function to be implemented later which
returns a number rounded to nearest 1,000.

so just mock it as
def get_amount():
    return 1000

and then just do that number / 4,000,000 to get fill height.

fill_height = get_amount()/4000000

if you can construct the image based on that, we'll find the rest.  I think
@tdfischer can get that quickly once she's around.

**Comment by masparasol** [comment]
Cool. I hack at Noisebridge on Tuesdays where I co-host free code camp with some awesome ppls. I will get group support to pull this together then. Thanks! :)

**Comment by marcidy** [comment]
oh we've definitely met then!

That's awesome, there's a bunch of other stuff if ppl want projects to work
on.

**Comment by masparasol** [comment]
Oh cool. Yeah, my name is Paul. 
If there a wish list of stuff to hack together on the site posted somewhere?

**Comment by marcidy** [comment]
not really.  we want people to raise issues here on GitHub to track them,
but only a small number of people do it.

plus not everything is relevant to infrastructure.   like someone is
working on ordibooth, which is space related, but has nothing to do with
core infrastructure.

I've attempted to create a Trello board more than once to get people to
post things there, but no avail.

The 'projects' board on discuss might work, that seems to have a good mix
of visibility and will grow with the project with a goo history of
discussion about each one. But if you have ideas for thing NB can use, go
crazy.  I would love if a lot of people worked on NB a little but at a
time.

and experience doesn't matter at all, there's no deadlines or money
involved, so who cares, we're all just hacking on this stuff

**Comment by masparasol** [comment]
Sounds like a plan! :)

**Comment by marcidy** [comment]
ok, based on above going to close the PR and we'll go in the direction we chatted about.  Thanks!

**Pull request closed without merging**
