### PR TITLE
Add more users admin access to earl.

### PR DESCRIPTION
**Pull request by SuperQ**
Closes: https://github.com/noisebridge/infrastructure/issues/162

### CODE REVIEW

**Comment by SuperQ** [comment]
Just waiting to find out what to do about the keys.

**Comment by marcidy** [comment]
I pinged 'em.  Does this grab the key each deploy?

**Comment by SuperQ** [comment]
Yes, each deploy refreshes keys automatically from github.

**Comment by SuperQ** [comment]
Deployed

**Pull request merged**
