### PR TITLE
remove secret email from alias as i don't know the person and i want …

### PR DESCRIPTION
**Pull request by ruthgrace**
…to be able to give others the ansible vault password so i'm not the only one

### CODE REVIEW

**Comment by SuperQ** [comment]
Reminds me, I have a branch that cleans up the aliases to simplify the structure such that most of it doesn't need to be secret anymore. Simplifies the editing.

**Comment by ruthgrace** [comment]
oh, that would be awesome!

The emails should still go to root, right? Which should in turn go to
myself and R. i have no idea what that alias was used for... do you have
any clues?

**Comment by SuperQ** [comment]
I don't know that alias was intended for. I will check with some other old NB folks who may know.

**Comment by radii** [comment]
The chillingeffects address was intended to service the following scenario:
* Alice publishes something on the NB wiki that pisses off Bob
* Bob sends a takedown notice to Noisebridge (IIRC the address is legal-demands@ or something)
* `/etc/aliases` automatically forwards the takedown notice to another nonprofit which has an automated process to catalog and track such things

As far as I know, the "another nonprofit" no longer operates the same way as it used to, the followon project is https://www.lumendatabase.org/ but I don't believe Noisebridge ever did anything to get set up with them.

This was documented on a wiki page titled "Memory hole" or something like that.

**Comment by SuperQ** [comment]
Thanks @radii. Based on that, the new alias change for `legal-demands@noiesbridge.net` seems fine.

**Pull request merged**
