### PR TITLE
Migrate to cloudalchemy.coredns role

### PR DESCRIPTION
**Pull request by SuperQ**
Swap out the home-grown coredns role for cloudalchemy.coredns.
* Simplify zone configs into a map.
* Convert from an inline Corefile templates to a template files.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Marking this draft until https://github.com/cloudalchemy/ansible-coredns/pull/56 is merged so it supports the dnssec keys.

**Review by croepha — APPROVED** [review]
This all looks good to me.  I should mention that I'm not ramped up on Ansible or CoreDNS, but I'm sure that you know what you are doing

**Comment by SuperQ** [comment]
Deployed

**Comment by croepha** [comment]
cool, thanks

**Pull request merged**
