### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by SuperQ**
Run ansible-lint in CI.

### CODE REVIEW

**Comment by marcidy** [comment]
Are the checks failing is part of bootstrapping CI into a build that doesn't have it?

**Comment by marcidy** [comment]
on, nm, actively being updated, ha

**Comment by SuperQ** [comment]
@marcidy I intentionally didn't fix one error to make sure the CI did the right thing. :grin:

**Comment by marcidy** [comment]
The failure was a success!

**Comment by SuperQ** [comment]
Task failed successfully!

**Pull request merged**
