### PR TITLE
add communityoutreach alias, with myself as the only recipient for now

### PR DESCRIPTION
**Pull request by ruthgrace**
The added text is

```
# Community outreach alias (not a mailman list)
communityoutreach: ruthgracewong@gmail.com
```

### CODE REVIEW

**Comment by SuperQ** [comment]
LGTM, but I would suggest `community-outreach` is a little less word salad.

**Comment by ruthgrace** [comment]
great suggestion! i updated it. thank you!

**Comment by ruthgrace** [comment]
had to do some finagling to get the merge of the encrypted file to work

**Comment by SuperQ** [comment]
Yea, doing simultaneous edits of the encrypted blobs can be a pain.

One thing we could do is convert the big blob into a series of encrypted strings for each of the aliases.

**Pull request merged**
