### PR TITLE
give ruth permissions

### PR DESCRIPTION
**Pull request by ruthgrace**
I'd like to give myself permissions to deploy the noisebridge.net website. Am I on the right track with this PR?

### CODE REVIEW

**Comment by rizend** [comment]
These look right to me for adding you to the m* servers.  I mangled the configuration to allow me to deploy to a local VM and it successfully added a `ruthgrace` user as expected.

**Comment by SuperQ** [comment]
This looks correct. We don't really have an access agreement, but be aware that getting access to all our infra comes with some responsibility.

* You need to fixing anything you break.
* You are responsible for the privacy of the users/members/public.
* You are responsible for keeping things secure.

If this sounds like something you're willing to take on, I'll approve this.

**Comment by old-noisebridger** [comment]
> permissions to deploy the noisebridge.net website.

...

> getting root access to all our infra.

that escalated quickly

**Comment by ruthgrace** [comment]
Yes, i am willing to take on all those things. I also plan to pair with
someone the first time I deploy to make sure I know how to roll back, etc.

**Comment by SuperQ** [comment]
This is deployed.

**Comment by ruthgrace** [comment]
Thanks!!! :D

**Pull request merged**
