### PR TITLE
Page for gala

### PR DESCRIPTION
**Pull request by rizend**
This PR adds a page for the upcoming gala fundraiser.

--------

Was Todo:
- ~~copy gala background image from discourse to the noisebridge.net site~~
- ~~run by someone who knows more about the gala~~

### CODE REVIEW

**Comment by rizend** [comment]
@SuperQ would you be able to deploy this this weekend?

**Comment by SuperQ** [comment]
@rizend Yea, I can deploy it any time this weekend. Just let me know when.

**Comment by rizend** [comment]
@SuperQ it can be deploy now; thanks!

**Comment by SuperQ** [comment]
One thing to note, it's probably easier to just link to a wiki page in the future. The whole point of the website being a wiki was to make it easier to edit.

IMO we should just drop the whole static content thing for the main site.

**Comment by old-noisebridger** [comment]
> One thing to note, it's probably easier to just link to a wiki page in the future. The whole point of the website being a wiki was to make it easier to edit.
> 
> IMO we should just drop the whole static content thing for the main site.

:+1:

**Pull request merged**
